######Use nginx to serve static files
FROM nginx:latest

# Remove default nginx HTML
RUN rm -rf /usr/share/nginx/html/*

# Copy your site to nginx HTML folder
COPY . /usr/share/nginx/html

#Expose port 80
EXPOSE 80
